databus:
  appName: DataBus
  databaseFileName: databus.sqlite
  configFileName: config.json
  repositories: repositories.json
  pluginInstallLocation: PluginFolder
  pluginRespLocation: PluginRepo
  remoteRespUri: http://localhost:3005/DataBus-Etl/PluginRepo/plugins.json
server:
  port: 2205
spring:
  quartz:
    job-store-type: memory

logging:
  level:
    org:
      quartz: debug