databus:
  appName: DataBus
  databaseFileName: databus.sqlite
  configFileName: config.json
  repositories: repositories.json
  pluginLocation: PluginFolder
  remoteRespUri: https://advancedproductivity.github.io/DataBus-Etl/PluginRepo/plugins.json
server:
  port: 2205
