databus:
  appName: DataBus
  databaseFileName: databus.sqlite
  configFileName: config.json
  repositories: repositories.json
  pluginInstallLocation: PluginFolder
  pluginRespLocation: PluginRepo
  remoteRespUri: https://advancedproductivity.github.io/DataBus-Etl/PluginRepo/plugins.json
server:
  port: 2205
spring:
  quartz:
    job-store-type: memory
