databus:
  appName: DataBus
  databaseFileName: databus.sqlite
  configFileName: config.json
  remoteUri: https://advancedproductivity.github.io/DataBus-Etl/PluginRepo/plugins.json
server:
  port: 2205
